Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false


Style/AsciiComments:
  Enabled: false

Style/MethodMissing:
  Enabled: false
