version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    depends_on:
      - mongo
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      BASIC_AUTH_USERNAME: 'admin'
      BASIC_AUTH_PASSWORD: 'pass'

  mongo:
    image: mongo:latest
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
