name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Check MongoDB connection
        run: |
          until nc -z localhost 27017; do
            echo Waiting for MongoDB to start...
            sleep 1
          done

      - name: Run tests
        run: bundle exec rspec
